### ISSUE TITLE
set up travis-ci automated testing

### ISSUE THREAD

**Issue by skyebend** [statnet/ergm.terms.contrib#2]
need to automate CRAN checks on commit

**Comment by skyebend** [comment]
Thanks @mbojan !   https://travis-ci.org/statnet/ergm.terms.contrib   Although, is there a way to mask the .travis.yml file from getting flagged on cran check?  I think the last package I did it in the directory above, but that made checking out the package  and install_github() require additional args.

**Comment by mbojan** [comment]
Ahh yes. Forgot about that. Fixing now.
